print('Nos campos:\nSalario Fixo, Porcentagem da Comissão e Vendas no Mês digite apenas números.')
print('Não precisa comverter a taxa de juros para decimal.')
print('Digite apenas os valores numéricos')
print('Utilize ponto ao invés de vírgula para representar números decimais')
print('O Campo: Nome do funcionário não acentos e pode ser deixado em branco.\n')
pessoa = input('Nome do Funcionário: ')
fixo = float(input('\nSalario Fixo: '))
porcentagem = float(input('\nPorcentagem da Comissão: '))
venda = float(input('\nVendas do Mês: '))
salario = fixo + (porcentagem / 100 * venda)
print('\nO salário de',pessoa, 'é de: R$',"%.2f"%salario,'\n')
input('Pressione ENTER para sair')
